feat: added md not completed
Marlyse22/gitlearning pull request #2
Opened 2023-08-22 23:47 UTC by J-Ben

#1 
We try some non certains feature

2023-08-22 23:50 UTC, Marlyse22 commented
Please change the content

2023-08-22 23:53 UTC, Marlyse22 requested changes

2023-08-22 23:53 UTC, Marlyse22 commented on pr_not_okay/not_okay.md
Add more elements

2023-08-22 23:57 UTC, J-Ben commented on pr_not_okay/not_okay.md
okay it's done

2023-08-23 00:01 UTC, Marlyse22 approved these changes
Everything is okay

2023-08-23 00:02 UTC, merged